parameters:
#    mz_inventory.example.class: mz\InventarioBundle\Example

services:
#    mz_inventory.example:
#        class: %mz_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mz_inventory.form.type.display:
        class: mz\InventoryBundle\Form\Type\DisplayType
        arguments:
            - "%display%"
        tags:
            - { name: form.type, alias: display }